package heroku.robot

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class HerokuFirstUserVisit extends Simulation {

	val httpProtocol = http
		.baseUrl("https://bookrobot-front.herokuapp.com")
		.acceptHeader("image/webp,*/*")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("en-US,en;q=0.5")
		.userAgentHeader("Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0")

	val headers_0 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"If-Modified-Since" -> "Wed, 31 Jul 2019 06:56:14 GMT",
		"If-None-Match" -> """W/"297-16c46d0a2b0"""",
		"Upgrade-Insecure-Requests" -> "1")

	val headers_1 = Map(
		"If-Modified-Since" -> "Wed, 31 Jul 2019 06:56:14 GMT",
		"If-None-Match" -> """W/"4d67-16c46d0a2b0"""")

	val headers_2 = Map(
		"If-Modified-Since" -> "Wed, 31 Jul 2019 06:56:14 GMT",
		"If-None-Match" -> """W/"12fc-16c46d0a2b0"""")

	val headers_3 = Map(
		"Accept" -> "application/json, text/plain, */*",
		"Origin" -> "https://bookrobot-front.herokuapp.com")

	val headers_6 = Map(
		"Accept" -> "application/json, text/plain, */*",
		"Content-Type" -> "application/json",
		"Origin" -> "https://bookrobot-front.herokuapp.com")

	val headers_7 = Map(
		"Accept" -> "*/*",
		"Access-Control-Request-Headers" -> "content-type",
		"Access-Control-Request-Method" -> "POST",
		"Origin" -> "https://bookrobot-front.herokuapp.com")

    val uri1 = "https://emp-scs-uat.img-osdw.pl/img-p/1/kipwn/92031d68/std/73-b9/105534980o.jpg"
    val uri3 = "https://bookrobotja7.herokuapp.com"
    val uri4 = "https://www.swiatksiazki.pl/media/catalog/product/cache/b194688dfba11ab51374da7d8ad52d29"

	val chain_0 = // start
		exec(http("request_0")
			.get("/home")
			.headers(headers_0))
		.pause(1)
		.exec(http("request_1")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_2")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_3")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(15)
		// registration
		.exec(http("request_4")
			.get("/signup")
			.headers(headers_0))
		.pause(949 milliseconds)
		.exec(http("request_5")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.pause(18)
		// new account creation
		//.exec(http("request_6")
			//.post(uri3 + "/auth/sign_up")
			//.headers(headers_6)
			//.body(RawFileBody("heroku/robot/herokufirstuservisit/0006_request.json")))
		//.pause(15)
		.exec(http("request_7")
			.options(uri3 + "/auth/sign_in")
			.headers(headers_7))
		//	wrong password pass by users
		.exec(http("request_8")
			.post(uri3 + "/auth/sign_in")
			.headers(headers_6)
			.body(RawFileBody("src/test/resources/scala/request-bodies/0008_request.json"))
			.check(status.is(401)))
		.pause(5)
		//	login
		.exec(http("request_9")
			.post(uri3 + "/auth/sign_in")
			.headers(headers_6)
			.body(RawFileBody("src/test/resources/scala/request-bodies/0009_request.json")))
		.exec(http("request_10")
			.get("/home")
			.headers(headers_0))
		.pause(959 milliseconds)
		.exec(http("request_11")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_12")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_13")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(13)
		// checking all books on first page
		.exec(http("request_14")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/francja-smak-i-piekno,p100673493.html")
			.headers(headers_3))
		.pause(5)
		.exec(http("request_15")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_16")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_17")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(1)
		.exec(http("request_18")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/szczescie-za-horyzontem-krystyna-mirek,p100692859.html")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_19")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_20")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_21")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(1)
		.exec(http("request_22")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/zimowy-wiatr-na-twojej-twarzy-carla-montero,p100620867.html")
			.headers(headers_3))
		.pause(1)
		.exec(http("request_23")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_24")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_25")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_26")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/lets-english-angielski-dla-4-latkow-praca-zbiorowa,p100578376.html")
			.headers(headers_3))
		.pause(1)
		.exec(http("request_27")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_28")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_29")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(1)
		.exec(http("request_30")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/lets-english-angielski-dla-4-latkow-praca-zbiorowa,p100578376.html")
			.headers(headers_3))
		.pause(1)
		.exec(http("request_31")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_32")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_33")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_34")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/lets-english-angielski-dla-4-latkow-praca-zbiorowa,p100578376.html")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_35")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_36")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_37")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_38")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/posciel-bawelniana-160x200-70x80-wenecja-lodka,p100653602.html")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_39")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_40")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_41")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_42")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/donica-oslonka-cynkowa-42x16x20-cm,p100672776.html")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_43")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_44")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_45")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(1)
		.exec(http("request_46")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/uczyc-sie-ze-zwierzetami-to-zabawa,p100727098.html")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_47")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_48")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_49")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_50")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/nieznajomi-ursula-poznanski,p100700578.html")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_51")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_52")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_53")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_54")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/serce-amicis-edmund-de,p100626492.html")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_55")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_56")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_57")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_58")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/nic-oprocz-strachu-magdalena-knedler,p100420363.html")
			.headers(headers_3))
		.pause(1)
		.exec(http("request_59")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_60")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_61")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_62")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/proba-milosci-miroslawa-kareta,p100732521.html")
			.headers(headers_3))
		.pause(1)
		.exec(http("request_63")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_64")
			.get("/assets/img/logo.png")
			.headers(headers_1))

val chain_1 = exec(http("request_65")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_66")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/stolik-z-drewna-tekowego-pieniek,p100644318.html")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_67")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_68")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_69")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_70")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/posciel-bawelniana-160x200-2x70x80-kolorowa-mozaika,p100661557.html")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_71")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_72")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_73")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(6)
		.exec(http("request_74")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/podwojna-donica-oslonka-cynkowa,p100672777.html")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_75")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_76")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_77")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(5)
		.exec(http("request_78")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/zdrowe-kalorie-straczki-kasze-pestki-owoce,p100669164.html")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_79")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_80")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_81")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(4)
		.exec(http("request_82")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/zanim-zniknela-jane-shemilt,p100725391.html")
			.headers(headers_3))
		.pause(2)
		.exec(http("request_83")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_84")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_85")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(8)
		.exec(http("request_86")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/praktyczny-kurs-mowienia-i-rozmawiania-jezyk-angielski-beata-pawlikowska,p100502197.html")
			.headers(headers_3))
		.pause(1)
		.exec(http("request_87")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_88")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_89")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_90")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/deska-do-ryb,p100275557.html")
			.headers(headers_3))
		.pause(5)
		.exec(http("request_91")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_92")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_93")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_94")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/ania-na-uniwersytecie-maud-montgomery-lucy,p100735396.html")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_95")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_96")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_97")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_98")
			.get(uri3 + "/bookUrl/https://www.ravelo.pl/czerwony-testament-tom-2-de-montpin-xavier,p100729843.html")
			.headers(headers_3))
		.pause(3)
		.exec(http("request_99")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_100")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_101")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(2)
		// next page
		.exec(http("request_102")
			.get(uri3 + "/books/pagination/next")
			.headers(headers_3))
		.pause(253 milliseconds)
		.exec(http("request_103")
			.get(uri1))
		.exec(http("request_104")
			.get(uri4 + "/4/x/4x99906536040.jpg"))
		.exec(http("request_105")
			.get(uri4 + "/2/x/2x99906536420.jpg"))
		.exec(http("request_106")
			.get(uri4 + "/4/1/4199906536041.jpg"))
		.exec(http("request_107")
			.get(uri4 + "/5/8/5899906535758.jpg"))
		.exec(http("request_108")
			.get(uri4 + "/6/x/6x99906536260.jpg"))
		.exec(http("request_109")
			.get(uri4 + "/2/7/2799906536427.jpg"))
		.exec(http("request_110")
			.get(uri4 + "/5/5/5599906535655.jpg"))
		.exec(http("request_111")
			.get(uri4 + "/3/4/3499906535634.jpg"))
		.exec(http("request_112")
			.get(uri4 + "/x/8/x899906535608.jpg"))
		.exec(http("request_113")
			.get(uri4 + "/8/x/8x99906535580.jpg"))
		.exec(http("request_114")
			.get(uri4 + "/8/6/8699906535586.jpg"))
		.exec(http("request_115")
			.get(uri4 + "/4/9/4999906535549.jpg"))
		.exec(http("request_116")
			.get(uri4 + "/8/4/8499906535484.jpg"))
		.exec(http("request_117")
			.get(uri4 + "/9/3/9399906535493.jpg"))
		.exec(http("request_118")
			.get(uri4 + "/1/1/1199906533311.jpg"))
		.exec(http("request_119")
			.get(uri4 + "/8/1/8199906532481.jpg"))
		.exec(http("request_120")
			.get(uri4 + "/9/6/9699906535496.jpg"))
		.exec(http("request_121")
			.get(uri4 + "/9/4/9499906532694.jpg"))
		.exec(http("request_122")
			.get(uri4 + "/7/5/7599906532375.jpg"))
		.pause(6)
		// checking last book
		.exec(http("request_123")
			.get(uri3 + "/bookUrl/https://www.swiatksiazki.pl/outlet-droga-karola-wojtyly-tom-4-do-domu-ojca-ostatnia-dekada-6532375-ksiazka.html")
			.headers(headers_3))
		.pause(4)
		.exec(http("request_124")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_125")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_126")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))
		.pause(4)
		// logout
		.exec(http("request_127")
			.get("/home")
			.headers(headers_0))
		.pause(946 milliseconds)
		.exec(http("request_128")
			.get("/assets/img/logo.png")
			.headers(headers_1))
		.exec(http("request_129")
			.get("/assets/img/sort.png")
			.headers(headers_2))
		.exec(http("request_130")
			.get(uri3 + "/books/pagination")
			.headers(headers_3))

	val scn = scenario("HerokuFirstUserVisit").exec(
		chain_0, chain_1)

	setUp(scn.inject(atOnceUsers(10))).protocols(httpProtocol)
}
