= README

== ABOUT ROBOT PROJECT

image:https://jenkins-nasz-pan.pl/sonar/api/project_badges/measure?project=edition.academy.seventh%3Arobot&metric=alert_status[Quality Gate Status]

Robot collects information about books on promotion and those available for
free in various libraries. Some through their REST APIs, some through screen-
scraping. Information is persisted in the database and there is a simple
reporting module.

== PREREQUISITES

IMPORTANT: Before coding, first of all, you have to (by using terminal) go into a `git-hooks` directory,
use a command `chmod +x add-hooks` and next `./add-hooks` to activate the `git hooks`. They will prevent git commits
that prevent the project from building.

=== System requirements

* Ubuntu 18.04
* Java 11.0.4 OpenJDK
* Maven 3.3.9
* Internet connection

=== Others

Clone this repository to your desired directory.

Prerequisites for running tests are described in <<anchor-1, *RUNNING*>> section.
Prerequisites for running backend application are described in <<anchor-2, *RUNNING*>> section.

== RUNNING

=== Tests

[[anchor-1]]To run integration or full scope of tests you need to:

* have active H2 database on port `9092` with name `test` and credentials
defined as one in `H2Connector.java`, or
* change protocol defined in `H2Connector.java`
(`javax.persistence.jdbc.url`) used by H2 database from `tcp` to `mem`.

==== Full scope of tests

Go into a main project's directory using terminal and use `mvn clean verify` command
to run unit, integration and performance tests.

==== Integration tests

Go into a main project's directory using terminal
and use `mvn clean test-compile failsafe:integration-test` command
to only integration tests.

==== Performance test

Go into a main project's directory using terminal and use `mvn clean gatling:test` command
to run only performance test. Test is performed by open source tool `Gatling`.
This test is part of integration tests scope by default.

==== Unit tests:

Go into a main project's directory using terminal and use `mvn clean test` command
to run only unit tests.

=== Application

==== Backend

[[anchor-2]]To run backend part of application you need to have unused port 8080.
If it is not a case you have to uncomment line 1 in `application.properties`.
Then application will start at pot `8085`.

To start application use in terminal (main project directory):

* `mvn clean install -Dmaven.test.skip=true -Dgatling.skip=true` and
then `java -jar target/robot-0.1.jar` commands, or
* `mvn spring-boot:run` command.

==== Frontend

To run frontend part of application read this
https://github.com/marcinogo/robot-front/blob/master/README.md[robot-front README].

== USAGE

=== Live version

Application is deployed with frontend part on https://bookrobot-front.herokuapp.com/home[*Heroku* server].
Unauthorized user can check information about books with promotion from various bookshops and check details
about promotions history, sort books, choose bookshop he / she is interested in and go to next / previous pages.

User can also sign in or sign up to perform additional actions:

* Admin can start information collection manually to update data,
* User can perform same action as

=== Local version
